 language: generic
 sudo: required
 services:
  - docker

before_install:
  - docker build -t claudineicaetano/react-docker-aws-ci-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true claudineicaetano/react-docker-aws-ci-travis npm run test